/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ActionRequest : The request to stop, pause or resume

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionRequest {
    /// The action of the request, should be stop, pause or resume
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Action>,
}

impl ActionRequest {
    /// The request to stop, pause or resume
    pub fn new() -> ActionRequest {
        ActionRequest { action: None }
    }
}

/// The action of the request, should be stop, pause or resume
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "pause")]
    Pause,
    #[serde(rename = "resume")]
    Resume,
}

impl Default for Action {
    fn default() -> Action {
        Self::Stop
    }
}
