/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ComponentHealthStatus : The health status of component

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComponentHealthStatus {
    /// The component name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The health status of component. Is either \"healthy\" or \"unhealthy\".
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// (optional) The error message when the status is \"unhealthy\"
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl ComponentHealthStatus {
    /// The health status of component
    pub fn new() -> ComponentHealthStatus {
        ComponentHealthStatus {
            name: None,
            status: None,
            error: None,
        }
    }
}
