/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigurationsResponseScanAllPolicy {
    /// The type of scan all policy, currently the valid values are \"none\" and \"daily\"
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "parameter", skip_serializing_if = "Option::is_none")]
    pub parameter: Option<Box<crate::models::ConfigurationsResponseScanAllPolicyParameter>>,
}

impl ConfigurationsResponseScanAllPolicy {
    pub fn new() -> ConfigurationsResponseScanAllPolicy {
        ConfigurationsResponseScanAllPolicy {
            r#type: None,
            parameter: None,
        }
    }
}
