/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Errors : The error array that describe the errors got during the handling of request

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Errors {
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::Error>>,
}

impl Errors {
    /// The error array that describe the errors got during the handling of request
    pub fn new() -> Errors {
        Errors { errors: None }
    }
}
