/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Icon {
    /// The content type of the icon
    #[serde(rename = "content-type", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// The base64 encoded content of the icon
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl Icon {
    pub fn new() -> Icon {
        Icon {
            content_type: None,
            content: None,
        }
    }
}
