/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InternalConfigurationValue {
    /// The value of current config item
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    /// The configure item can be updated or not
    #[serde(rename = "editable", skip_serializing_if = "Option::is_none")]
    pub editable: Option<bool>,
}

impl InternalConfigurationValue {
    pub fn new() -> InternalConfigurationValue {
        InternalConfigurationValue {
            value: None,
            editable: None,
        }
    }
}
