/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// NativeReportSummary : The summary for the native report

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NativeReportSummary {
    /// id of the native scan report
    #[serde(rename = "report_id", skip_serializing_if = "Option::is_none")]
    pub report_id: Option<String>,
    /// The status of the report generating process
    #[serde(rename = "scan_status", skip_serializing_if = "Option::is_none")]
    pub scan_status: Option<String>,
    /// The overall severity
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
    /// The seconds spent for generating the report
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i64>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<crate::models::VulnerabilitySummary>>,
    /// The start time of the scan process that generating report
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    /// The end time of the scan process that generating report
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    /// The complete percent of the scanning which value is between 0 and 100
    #[serde(rename = "complete_percent", skip_serializing_if = "Option::is_none")]
    pub complete_percent: Option<i32>,
    #[serde(rename = "scanner", skip_serializing_if = "Option::is_none")]
    pub scanner: Option<Box<crate::models::Scanner>>,
}

impl NativeReportSummary {
    /// The summary for the native report
    pub fn new() -> NativeReportSummary {
        NativeReportSummary {
            report_id: None,
            scan_status: None,
            severity: None,
            duration: None,
            summary: None,
            start_time: None,
            end_time: None,
            complete_percent: None,
            scanner: None,
        }
    }
}
