/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OidcCliSecretReq {
    /// The new secret
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl OidcCliSecretReq {
    pub fn new() -> OidcCliSecretReq {
        OidcCliSecretReq { secret: None }
    }
}
