/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PayloadFormat : Webhook supported payload format type collections.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayloadFormat {
    /// Webhook supported notify type.
    #[serde(rename = "notify_type", skip_serializing_if = "Option::is_none")]
    pub notify_type: Option<String>,
    /// The supported payload formats for this notify type.
    #[serde(rename = "formats", skip_serializing_if = "Option::is_none")]
    pub formats: Option<Vec<String>>,
}

impl PayloadFormat {
    /// Webhook supported payload format type collections.
    pub fn new() -> PayloadFormat {
        PayloadFormat {
            notify_type: None,
            formats: None,
        }
    }
}
