/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PingOidcRequest {
    /// The URL of OIDC endpoint to be tested.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Whether the certificate should be verified
    #[serde(rename = "verify_cert", skip_serializing_if = "Option::is_none")]
    pub verify_cert: Option<bool>,
}

impl PingOidcRequest {
    pub fn new() -> PingOidcRequest {
        PingOidcRequest {
            url: None,
            verify_cert: None,
        }
    }
}
