/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMember {
    /// The role id 1 for projectAdmin, 2 for developer, 3 for guest, 4 for maintainer
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<i32>,
    #[serde(rename = "member_user", skip_serializing_if = "Option::is_none")]
    pub member_user: Option<Box<crate::models::UserEntity>>,
    #[serde(rename = "member_group", skip_serializing_if = "Option::is_none")]
    pub member_group: Option<Box<crate::models::UserGroup>>,
}

impl ProjectMember {
    pub fn new() -> ProjectMember {
        ProjectMember {
            role_id: None,
            member_user: None,
            member_group: None,
        }
    }
}
