/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUpdateReq {
    #[serde(rename = "hard", skip_serializing_if = "Option::is_none")]
    pub hard: Option<::std::collections::HashMap<String, i64>>,
}

impl QuotaUpdateReq {
    pub fn new() -> QuotaUpdateReq {
        QuotaUpdateReq { hard: None }
    }
}
