/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RegistryEndpoint : The style of the resource filter

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryEndpoint {
    /// The endpoint key
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The endpoint value
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl RegistryEndpoint {
    /// The style of the resource filter
    pub fn new() -> RegistryEndpoint {
        RegistryEndpoint {
            key: None,
            value: None,
        }
    }
}
