/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RegistryProviderCredentialPattern : The registry credential pattern

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryProviderCredentialPattern {
    /// The access key type
    #[serde(rename = "access_key_type", skip_serializing_if = "Option::is_none")]
    pub access_key_type: Option<String>,
    /// The access key data
    #[serde(rename = "access_key_data", skip_serializing_if = "Option::is_none")]
    pub access_key_data: Option<String>,
    /// The access secret type
    #[serde(rename = "access_secret_type", skip_serializing_if = "Option::is_none")]
    pub access_secret_type: Option<String>,
    /// The access secret data
    #[serde(rename = "access_secret_data", skip_serializing_if = "Option::is_none")]
    pub access_secret_data: Option<String>,
}

impl RegistryProviderCredentialPattern {
    /// The registry credential pattern
    pub fn new() -> RegistryProviderCredentialPattern {
        RegistryProviderCredentialPattern {
            access_key_type: None,
            access_key_data: None,
            access_secret_type: None,
            access_secret_data: None,
        }
    }
}
