/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RegistryProviderInfo : The registry provider info contains the base info and capability declarations of the registry provider

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryProviderInfo {
    #[serde(rename = "endpoint_pattern", skip_serializing_if = "Option::is_none")]
    pub endpoint_pattern: Option<Box<crate::models::RegistryProviderEndpointPattern>>,
    #[serde(rename = "credential_pattern", skip_serializing_if = "Option::is_none")]
    pub credential_pattern: Option<Box<crate::models::RegistryProviderCredentialPattern>>,
}

impl RegistryProviderInfo {
    /// The registry provider info contains the base info and capability declarations of the registry provider
    pub fn new() -> RegistryProviderInfo {
        RegistryProviderInfo {
            endpoint_pattern: None,
            credential_pattern: None,
        }
    }
}
