/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplicationTrigger {
    /// The replication policy trigger type. The valid values are manual, event_based and scheduled.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "trigger_settings", skip_serializing_if = "Option::is_none")]
    pub trigger_settings: Option<Box<crate::models::ReplicationTriggerSettings>>,
}

impl ReplicationTrigger {
    pub fn new() -> ReplicationTrigger {
        ReplicationTrigger {
            r#type: None,
            trigger_settings: None,
        }
    }
}
