/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplicationTriggerSettings {
    /// The cron string for scheduled trigger
    #[serde(rename = "cron", skip_serializing_if = "Option::is_none")]
    pub cron: Option<String>,
}

impl ReplicationTriggerSettings {
    pub fn new() -> ReplicationTriggerSettings {
        ReplicationTriggerSettings { cron: None }
    }
}
