/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReplicationTask : The replication task

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplicationTask {
    /// The ID of the task
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The ID of the execution that the task belongs to
    #[serde(rename = "execution_id", skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<i32>,
    /// The status of the task
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The ID of the underlying job that the task related to
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<String>,
    /// The operation of the task
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// The type of the resource that the task operates
    #[serde(rename = "resource_type", skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<String>,
    /// The source resource that the task operates
    #[serde(rename = "src_resource", skip_serializing_if = "Option::is_none")]
    pub src_resource: Option<String>,
    /// The destination resource that the task operates
    #[serde(rename = "dst_resource", skip_serializing_if = "Option::is_none")]
    pub dst_resource: Option<String>,
    /// The start time of the task
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    /// The end time of the task
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
}

impl ReplicationTask {
    /// The replication task
    pub fn new() -> ReplicationTask {
        ReplicationTask {
            id: None,
            execution_id: None,
            status: None,
            job_id: None,
            operation: None,
            resource_type: None,
            src_resource: None,
            dst_resource: None,
            start_time: None,
            end_time: None,
        }
    }
}
