/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplicationFilter {
    /// The replication policy filter type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The value of replication policy filter.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    /// matches or excludes the result
    #[serde(rename = "decoration", skip_serializing_if = "Option::is_none")]
    pub decoration: Option<String>,
}

impl ReplicationFilter {
    pub fn new() -> ReplicationFilter {
        ReplicationFilter {
            r#type: None,
            value: None,
            decoration: None,
        }
    }
}
