/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RetentionSelectorMetadata : retention selector

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetentionSelectorMetadata {
    #[serde(rename = "display_text", skip_serializing_if = "Option::is_none")]
    pub display_text: Option<String>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "decorations", skip_serializing_if = "Option::is_none")]
    pub decorations: Option<Vec<String>>,
}

impl RetentionSelectorMetadata {
    /// retention selector
    pub fn new() -> RetentionSelectorMetadata {
        RetentionSelectorMetadata {
            display_text: None,
            kind: None,
            decorations: None,
        }
    }
}
