/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RetentionMetadata : the tag retention metadata

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetentionMetadata {
    /// templates
    #[serde(rename = "templates", skip_serializing_if = "Option::is_none")]
    pub templates: Option<Vec<crate::models::RetentionRuleMetadata>>,
    /// supported scope selectors
    #[serde(rename = "scope_selectors", skip_serializing_if = "Option::is_none")]
    pub scope_selectors: Option<Vec<crate::models::RetentionSelectorMetadata>>,
    /// supported tag selectors
    #[serde(rename = "tag_selectors", skip_serializing_if = "Option::is_none")]
    pub tag_selectors: Option<Vec<crate::models::RetentionSelectorMetadata>>,
}

impl RetentionMetadata {
    /// the tag retention metadata
    pub fn new() -> RetentionMetadata {
        RetentionMetadata {
            templates: None,
            scope_selectors: None,
            tag_selectors: None,
        }
    }
}
