/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetentionRuleTrigger {
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
    #[serde(rename = "references", skip_serializing_if = "Option::is_none")]
    pub references: Option<serde_json::Value>,
}

impl RetentionRuleTrigger {
    pub fn new() -> RetentionRuleTrigger {
        RetentionRuleTrigger {
            kind: None,
            settings: None,
            references: None,
        }
    }
}
