/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RetentionRuleMetadata : the tag retention rule metadata

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetentionRuleMetadata {
    /// rule id
    #[serde(rename = "rule_template", skip_serializing_if = "Option::is_none")]
    pub rule_template: Option<String>,
    /// rule display text
    #[serde(rename = "display_text", skip_serializing_if = "Option::is_none")]
    pub display_text: Option<String>,
    /// rule action
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// rule params
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<crate::models::RetentionRuleParamMetadata>>,
}

impl RetentionRuleMetadata {
    /// the tag retention rule metadata
    pub fn new() -> RetentionRuleMetadata {
        RetentionRuleMetadata {
            rule_template: None,
            display_text: None,
            action: None,
            params: None,
        }
    }
}
