/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RobotCreated : The response for robot account creation.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RobotCreated {
    /// The ID of the robot
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// The name of the robot
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The secret of the robot
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The creation time of the robot.
    #[serde(rename = "creation_time", skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    /// The expiration date of the robot
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<i64>,
}

impl RobotCreated {
    /// The response for robot account creation.
    pub fn new() -> RobotCreated {
        RobotCreated {
            id: None,
            name: None,
            secret: None,
            creation_time: None,
            expires_at: None,
        }
    }
}
