/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleRequest {
    /// The role id 1 for projectAdmin, 2 for developer, 3 for guest, 4 for maintainer
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<i32>,
}

impl RoleRequest {
    pub fn new() -> RoleRequest {
        RoleRequest { role_id: None }
    }
}
