/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ScannerAdapterMetadata : The metadata info of the scanner adapter

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScannerAdapterMetadata {
    #[serde(rename = "scanner", skip_serializing_if = "Option::is_none")]
    pub scanner: Option<Box<crate::models::Scanner>>,
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<Vec<crate::models::ScannerCapability>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<::std::collections::HashMap<String, String>>,
}

impl ScannerAdapterMetadata {
    /// The metadata info of the scanner adapter
    pub fn new() -> ScannerAdapterMetadata {
        ScannerAdapterMetadata {
            scanner: None,
            capabilities: None,
            properties: None,
        }
    }
}
