/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ScanDataExportRequest : The criteria to select the scan data to export.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScanDataExportRequest {
    /// Name of the scan data export job
    #[serde(rename = "job_name", skip_serializing_if = "Option::is_none")]
    pub job_name: Option<String>,
    /// A list of one or more projects for which to export the scan data, currently only one project is supported due to performance concerns, but define as array for extension in the future.
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<i64>>,
    /// A list of one or more labels for which to export the scan data, defaults to all if empty
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<i64>>,
    /// A list of repositories for which to export the scan data, defaults to all if empty
    #[serde(rename = "repositories", skip_serializing_if = "Option::is_none")]
    pub repositories: Option<String>,
    /// CVE-IDs for which to export data. Multiple CVE-IDs can be specified by separating using ',' and enclosed between '{}'. Defaults to all if empty
    #[serde(rename = "cveIds", skip_serializing_if = "Option::is_none")]
    pub cve_ids: Option<String>,
    /// A list of tags enclosed within '{}'. Defaults to all if empty
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<String>,
}

impl ScanDataExportRequest {
    /// The criteria to select the scan data to export.
    pub fn new() -> ScanDataExportRequest {
        ScanDataExportRequest {
            job_name: None,
            projects: None,
            labels: None,
            repositories: None,
            cve_ids: None,
            tags: None,
        }
    }
}
