/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SchedulerStatus : the scheduler status

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchedulerStatus {
    /// if the scheduler is paused
    #[serde(rename = "paused", skip_serializing_if = "Option::is_none")]
    pub paused: Option<bool>,
}

impl SchedulerStatus {
    /// the scheduler status
    pub fn new() -> SchedulerStatus {
        SchedulerStatus { paused: None }
    }
}
