/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ScheduleTask : the schedule task info

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleTask {
    /// the id of the Schedule task
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// the vendor type of the current schedule task
    #[serde(rename = "vendor_type", skip_serializing_if = "Option::is_none")]
    pub vendor_type: Option<String>,
    /// the vendor id of the current task
    #[serde(rename = "vendor_id", skip_serializing_if = "Option::is_none")]
    pub vendor_id: Option<i32>,
    /// the cron of the current schedule task
    #[serde(rename = "cron", skip_serializing_if = "Option::is_none")]
    pub cron: Option<String>,
    /// the update time of the schedule task
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl ScheduleTask {
    /// the schedule task info
    pub fn new() -> ScheduleTask {
        ScheduleTask {
            id: None,
            vendor_type: None,
            vendor_id: None,
            cron: None,
            update_time: None,
        }
    }
}
