/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartReplicationExecution {
    /// The ID of policy that the execution belongs to.
    #[serde(rename = "policy_id", skip_serializing_if = "Option::is_none")]
    pub policy_id: Option<i64>,
}

impl StartReplicationExecution {
    pub fn new() -> StartReplicationExecution {
        StartReplicationExecution { policy_id: None }
    }
}
