/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SupportedWebhookEventTypes : Supported webhook event types and notify types.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupportedWebhookEventTypes {
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<Vec<String>>,
    #[serde(rename = "notify_type", skip_serializing_if = "Option::is_none")]
    pub notify_type: Option<Vec<String>>,
    #[serde(rename = "payload_formats", skip_serializing_if = "Option::is_none")]
    pub payload_formats: Option<Vec<crate::models::PayloadFormat>>,
}

impl SupportedWebhookEventTypes {
    /// Supported webhook event types and notify types.
    pub fn new() -> SupportedWebhookEventTypes {
        SupportedWebhookEventTypes {
            event_type: None,
            notify_type: None,
            payload_formats: None,
        }
    }
}
