/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TriggerRetentionExecutionRequest {
    #[serde(rename = "dry_run", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
}

impl TriggerRetentionExecutionRequest {
    pub fn new() -> TriggerRetentionExecutionRequest {
        TriggerRetentionExecutionRequest { dry_run: None }
    }
}
