/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSysAdminFlag {
    /// true-admin, false-not admin.
    #[serde(rename = "sysadmin_flag", skip_serializing_if = "Option::is_none")]
    pub sysadmin_flag: Option<bool>,
}

impl UserSysAdminFlag {
    pub fn new() -> UserSysAdminFlag {
        UserSysAdminFlag {
            sysadmin_flag: None,
        }
    }
}
