/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// WebhookTargetObject : The webhook policy target object.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookTargetObject {
    /// The webhook target notify type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The webhook target address.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// The webhook auth header.
    #[serde(rename = "auth_header", skip_serializing_if = "Option::is_none")]
    pub auth_header: Option<String>,
    /// Whether or not to skip cert verify.
    #[serde(rename = "skip_cert_verify", skip_serializing_if = "Option::is_none")]
    pub skip_cert_verify: Option<bool>,
    /// The type of webhook paylod format.
    #[serde(rename = "payload_format", skip_serializing_if = "Option::is_none")]
    pub payload_format: Option<String>,
}

impl WebhookTargetObject {
    /// The webhook policy target object.
    pub fn new() -> WebhookTargetObject {
        WebhookTargetObject {
            r#type: None,
            address: None,
            auth_header: None,
            skip_cert_verify: None,
            payload_format: None,
        }
    }
}
