/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// WebhookJob : The webhook job.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookJob {
    /// The webhook job ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// The webhook policy ID.
    #[serde(rename = "policy_id", skip_serializing_if = "Option::is_none")]
    pub policy_id: Option<i64>,
    /// The webhook job event type.
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    /// The webhook job notify type.
    #[serde(rename = "notify_type", skip_serializing_if = "Option::is_none")]
    pub notify_type: Option<String>,
    /// The webhook job status.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The webhook job notify detailed data.
    #[serde(rename = "job_detail", skip_serializing_if = "Option::is_none")]
    pub job_detail: Option<String>,
    /// The webhook job creation time.
    #[serde(rename = "creation_time", skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    /// The webhook job update time.
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl WebhookJob {
    /// The webhook job.
    pub fn new() -> WebhookJob {
        WebhookJob {
            id: None,
            policy_id: None,
            event_type: None,
            notify_type: None,
            status: None,
            job_detail: None,
            creation_time: None,
            update_time: None,
        }
    }
}
