/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// WebhookPolicy : The webhook policy object

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPolicy {
    /// The webhook policy ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// The name of webhook policy.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The description of webhook policy.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The project ID of webhook policy.
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "targets", skip_serializing_if = "Option::is_none")]
    pub targets: Option<Vec<crate::models::WebhookTargetObject>>,
    #[serde(rename = "event_types", skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<String>>,
    /// The creator of the webhook policy.
    #[serde(rename = "creator", skip_serializing_if = "Option::is_none")]
    pub creator: Option<String>,
    /// The create time of the webhook policy.
    #[serde(rename = "creation_time", skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    /// The update time of the webhook policy.
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
    /// Whether the webhook policy is enabled or not.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl WebhookPolicy {
    /// The webhook policy object
    pub fn new() -> WebhookPolicy {
        WebhookPolicy {
            id: None,
            name: None,
            description: None,
            project_id: None,
            targets: None,
            event_types: None,
            creator: None,
            creation_time: None,
            update_time: None,
            enabled: None,
        }
    }
}
